Eshop/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path , include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Store.urls')),
    path('accounts/' , include("accounts.urls")),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Store/urls.py
from django.contrib import admin
from django.urls import path
from .views .index import index ,product_detail,addtocart,validate_payment,cart,checkout,order


urlpatterns = [
    path('', index , name='indexpage'),
    path('product_detail/<str:slug>',product_detail , name='product_detail'),
    path('add_to_cart/<str:slug>/<str:size>',addtocart , name='addtocart'),
    path("cart" , cart , name='cart'),
    path('order', order , name='order'),
    path('checkout' , checkout , name="checkout"),
    path('validate_payment' , validate_payment , )
]

Store/models/product.py
from django.db import models
from django .contrib.auth .models import User

class slider(models.Model):
    slider = models.ImageField(upload_to = 'upload/slider/img', null=False)
    Show_Slider = models.BooleanField(default=True)

class TshirtProperty(models.Model):
    title = models.CharField(max_length=30, null=False)
    slug = models.CharField(max_length=30, null=False, unique=True)

    def __str__(self):
        return self.title

    # Don't create table in database using this property
    class Meta:
        abstract = True

class Occasion(TshirtProperty):  
    pass

class IdealFor(TshirtProperty):
    pass

class NeckType(TshirtProperty):
    pass

class Sleeve(TshirtProperty):
    pass

class Brand(TshirtProperty):
    pass

class Color(TshirtProperty):
    pass

class Tshirt(models.Model):
    tshirt_name = models.CharField(max_length=100, null=False)
    slug = models.CharField(max_length=200 , null=False , unique=True , default='')
    tshirt_Desc = models.CharField(max_length=100, null=True, blank=True)
    discount = models.IntegerField()
    tshirt_img = models.ImageField(upload_to='upload/img', null=False)
    tshirt_img2 = models.ImageField(upload_to='upload/img', null=True, blank=True)
    tshirt_img3 = models.ImageField(upload_to='upload/img', null=True , blank=True)
    occasion = models.ForeignKey(Occasion, on_delete=models.CASCADE)
    Ideal_for = models.ForeignKey(IdealFor, on_delete=models.CASCADE)
    Neck_type = models.ForeignKey(NeckType, on_delete=models.CASCADE)
    sleeve = models.ForeignKey(Sleeve, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    def __str__(self):
        return self.tshirt_name

class SizeVariant(models.Model):
    SIZES = (
        ('S', 'Small'),
        ('M', 'Medium'),
        ('L', 'Large'),
        ('XL', 'XL'),
        ('XXL', 'XXL'),
    )
    price = models.IntegerField()
    tshirt = models.ForeignKey(Tshirt, on_delete=models.CASCADE)
    size = models.CharField(choices=SIZES, max_length=5)

    def __str__(self):
        return f'{self.size}'

class Cart(models.Model):
    sizeVariant = models.ForeignKey(SizeVariant , on_delete=models.CASCADE)
    Quantity = models.IntegerField(default=1)
    user = models.ForeignKey(User , on_delete=models.CASCADE)

class Order(models.Model):
    OrderStatus = (
        ("PENDING" , "Pending"),
        ("PLACED" , "Placed"),
        ("CANCELED" , "Canceled"),
        ("COMPLETE" , "Complete"),
    )

    method = (
        ("COD","Cod"),
        ("ONLINE","Online"),
    )
    order_status = models.CharField(max_length=30, choices=OrderStatus)
    payment_method = models.CharField(max_length=30, choices=method)
    shipping_address = models.CharField(max_length=60 , null=False)
    phone = models.CharField(max_length=10, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.IntegerField(null=False)
    date = models.DateTimeField(null=False , auto_now_add=True)

class OrderItem(models.Model):
    order = models.ForeignKey(Order , on_delete=models.CASCADE)
    tshirt = models.ForeignKey(Tshirt , on_delete=models.CASCADE)
    size = models.ForeignKey(SizeVariant , on_delete=models.CASCADE)
    quantity = models.IntegerField(null=False)
    price = models.IntegerField(null=False)
    date = models.DateTimeField(null=False, auto_now_add=True)

class Payment(models.Model):
    order = models.ForeignKey(Order , on_delete=models.CASCADE)
    date = models.DateTimeField(null=False, auto_now_add=True)
    payment_status = models.CharField(max_length=30 , default="FAILED")
    payment_id = models.CharField(max_length=100)
    payment_request_id = models.CharField(max_length=100 , unique=True , null=False)

Store/forms/checkout.py
from django.contrib.auth .forms import UserCreationForm ,AuthenticationForm
from django import forms
from Store .models .product import Order
from django.contrib.auth.models import User


class CheckForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['shipping_address', 'phone' , 'payment_method']

Store/views/index.py
from django.shortcuts import render , redirect 
from Store .models .product import  Order ,Tshirt , OrderItem , Payment ,slider , SizeVariant , \
    Cart , Occasion ,Color , IdealFor , Sleeve , NeckType , Brand
from math import floor
from django.contrib.auth.decorators import login_required
from Store .forms .checkout import CheckForm
from instamojo_wrapper import Instamojo
from Eshop .settings import API_KEY , AUTH_TOKEN
API = Instamojo(api_key=API_KEY, auth_token=AUTH_TOKEN, endpoint='https://test.instamojo.com/api/1.1/');
from django.core.paginator import Paginator
from urllib .parse import urlencode

def index(request):
    Slider = slider.objects.filter(Show_Slider=True)
    data = request.GET
    page = data.get('page')
    if page is None or page == '':
        page = 1
    Brands = data.get('brand')
    Occations = data.get('occation')
    Idealfor = data.get('idealfor')
    sleeves = data.get('sleeve')
    necktypes = data.get('necktype')
    colors = data.get('color')
    occation = Occasion.objects.all()
    brand = Brand.objects.all()
    color = Color.objects.all()
    idealfor = IdealFor.objects.all()
    sleeve = Sleeve.objects.all()
    necktype = NeckType.objects.all()
    tshirt = Tshirt.objects.all()
    if Brands !="" and Brands != None:
        tshirt = tshirt.filter(brand__slug=Brands)
    if Occations !='' and Occations != None:
        tshirt = tshirt.filter(occasion__slug=Occations)
    if  Idealfor !='' and Idealfor != None:
        tshirt = tshirt.filter(Ideal_for__slug=Idealfor)
    if  sleeves !='' and sleeves != None:
        tshirt = tshirt.filter(sleeve__slug=sleeves)
    if necktypes != '' and necktypes != None:
        tshirt = tshirt.filter(Neck_type__slug=necktypes)
    if colors != '' and colors != None:
        tshirt = tshirt.filter(color__slug=colors)
    paginator = Paginator(tshirt , 5)
    page_obj = paginator.get_page(page)

    data = request.GET.copy()
    data['page']=''
    pageurl = urlencode(data)

    context = {
        'occation':occation,
        'brand':brand,
        'color':color,
        'idealfor':idealfor,
        'sleeve':sleeve,
        'necktype':necktype,
        'page_obj':page_obj,
        'Slider':Slider,
        'pageurl':pageurl
    }
    return render(request , 'index.html' , context=context)

def product_detail(request,slug):
    tshirt = Tshirt.objects.get(slug=slug)
    Size = request.GET.get('size')
    
    if Size is None:
        size = tshirt.sizevariant_set.all().order_by('price').first()
    else:
        size = tshirt.sizevariant_set.get(size=Size)
    size_price = size.price #price without discount
    sell_price = size_price - (size_price*(tshirt.discount)/100) #sell Price
    sell_price = floor(sell_price)
    context = {
        'tshirt':tshirt,
        'size_price':size_price,
        'sell_price':sell_price,
        'active_size': size

    }
    return render(request,'product_detail.html', context=context)


'''cart page '''
def cart(request):
    cart = request.session.get('cart')
    if cart is None:
        cart = []
    for c in cart:
        tshirt_id = c.get('tshirt')
        tshirt = Tshirt.objects.get(id=tshirt_id)
        c['size'] = SizeVariant.objects.get(tshirt=tshirt_id,size=c['size'])
        c['tshirt'] = tshirt
    context = {
        'cart':cart
    }
    return render(request , "cart.html" , context=context)
'''End cart page '''



'''add to cart manage '''
def addtocart(request , slug ,size):
    user = None
    if request.user.is_authenticated:
        user = request.user
    cart = request.session.get('cart') #supposed session in cart
    if cart is None:
        cart = []
    tshirt = Tshirt.objects.get(slug=slug)
    add_cart_for_anom_user(cart, size , tshirt)
    
    if user is not None:
        add_cart_database(user , size , tshirt)
    request.session['cart']=cart #create session assign the value of cart
    return_url = request.GET.get("return_url")
    return redirect(return_url)

def add_cart_database(user, size , tshirt):
    size = SizeVariant.objects.get(size=size, tshirt=tshirt)
    existing = Cart.objects.filter(user=user, sizeVariant=size)
    if len(existing) > 0:
        obj = existing[0]
        obj.Quantity = obj.Quantity + 1
        obj.save()
    else:
        c = Cart()
        c.user = user
        c.sizeVariant = size
        c.Quantity = 1
        c.save()

def add_cart_for_anom_user(cart , size , tshirt):
    flag = True
    for cart_obj in cart:
        t_id = cart_obj.get('tshirt')
        size_short = cart_obj.get('size')
        if t_id == tshirt.id and size == size_short:
            flag = False
            cart_obj['Quantity'] = cart_obj['Quantity'] + 1

    if flag:
        cart_obj = {
            'tshirt': tshirt.id,
            'size': size,
            'Quantity': 1
        }
        cart.append(cart_obj)
        
'''End cart manage '''


def clc_total_payable_amount(cart):
    total = 0
    for c in cart:
        dicount = c.get('tshirt').discount
        price = c.get('size').price
        sale_price = floor(price - (price*dicount/100))
        total_of_single_product = sale_price * c.get('Quantity')
        total = total + total_of_single_product
    return total


# @login_required(login_url='/accounts/login')
def order(request):
    user = request.user
    order = Order.objects.filter(user=user).order_by('-date').exclude(order_status='PENDING')
    print(order)
    context = {
        "order":order
    }
    return render(request , 'order.html' , context=context)

@login_required(login_url='/accounts/login')
def checkout(request):
    if request.method == 'GET':
        form = CheckForm()
        cart = request.session.get('cart')
        if cart is None:
            cart = []
        for c in cart:
            size_str = c.get('size')
            tshirt_id = c.get('tshirt')
            size_obj = SizeVariant.objects.get(size=size_str ,tshirt=tshirt_id)
            c['size']=size_obj
            c['tshirt']=size_obj.tshirt 
            context = {
                "checkoutform":form,
                "cart":cart 
            }
        return render(request , 'checkout_form.html' , context=context)

    else:
        form = CheckForm(request.POST)
        user = None
        if request.user.is_authenticated:
            user = request.user
            print("user = :",user)
        if form.is_valid():
            cart = request.session.get('cart')
            if cart is None:
                cart = []
            for c in cart:
                size_str = c.get('size')
                tshirt_id = c.get('tshirt')
                size_obj = SizeVariant.objects.get(size=size_str ,tshirt=tshirt_id)
                c['size']=size_obj
                c['tshirt']=size_obj.tshirt 
            shipping_add = form.cleaned_data.get('shipping_address')
            phone = form.cleaned_data.get('phone')
            payment_method = form.cleaned_data.get('payment_method')
            total = clc_total_payable_amount(cart)
            order = Order()
            order.shipping_address = shipping_add
            order.phone = phone
            order.payment_method = payment_method
            order.total = total
            order.order_status = "PENDING"
            order.user = user
            order.save()

            for c in cart:
                order_item = OrderItem()
                order_item.order = order
                size = c.get('size')
                tshirt = c.get('tshirt')
                order_item.price = floor(size.price-(size.price*tshirt.discount/100))
                order_item.quantity = c.get('Quantity')
                order_item.size = size
                order_item.tshirt = tshirt
                order_item.save()
            

            # Creating Payment
            response = API.payment_request_create(
            amount=order.total,
            purpose='Payment For Tshirt',
            send_email=True,
            buyer_name=f'{user.first_name} {user.last_name}',
            email=user.email,   
            redirect_url="http://localhost:8000/validate_payment"
            )
            print(response['payment_request'])
            payment_request_id=response['payment_request']['id']
            url=response['payment_request']['longurl']

            payment = Payment()
            payment.order = order
            payment.payment_request_id = payment_request_id
            payment.save()
            print(shipping_add , phone, payment_method , total)
            return redirect(url)
        else:
            return redirect('/checkout')


def validate_payment(request):
    user = None
    if request.user.is_authenticated:
        user = request.user
    payment_request_id = request.GET.get('payment_request_id')
    payment_id = request.GET.get('payment_id')
    print('patment Request Id =:',payment_request_id , "payment id =:", payment_id)
    response = API.payment_request_payment_status(payment_request_id,payment_id)
    status = response.get('payment_request').get('payment').get('status') # Payment status 
    print(status)   
    if status != 'Failed':
        try:
            payment = Payment.objects.get(payment_request_id=payment_request_id)
            payment.payment_id = payment_id
            payment.payment_status = status  
            payment.save()
            order = payment.order
            order.order_status = 'PLACED'
            order.save()
            cart = []
            request.session['cart']=cart
            Cart.objects.filter(user=user).delete()
            return redirect("order")
        except:
            return render(request ,  'payment_failed.html')
    # return render(request ,  'payment_failed.html')

Store/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>BEST DEAL</title>
  <link rel="icon" href="{% static 'img/small-logo.png' %}" type="image/icon type">
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <!-- bootstrap icon -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
  <!-- css -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- owl Carousel -->
  <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.css' }">
  <!-- js slider -->
  <link rel="stylesheet" href="{% static 'css/splide.min.css' %}">
  <!-- <link rel="stylesheet" href="css/splide.min.css"> -->
  <link rel="stylesheet" href="{% static 'css/splide-default.min.css' %}">
  <!-- AOS Animation -->
  <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

</head>

<!-- Nav Bar Start Here -->
<div class="container-fluid main-section-nav">
  <nav class="navbar navbar-expand-lg navbar-light middle-nav">
    <div class="container-fluid">
      <a class="navbar-brand" href="/"><img src="{% static 'img/logo/logo.png' %}" alt="" class="img-fluid logo"></a>
      <a href="/"><img src="{% static 'img/logo/small-logo.png' %}" class="img-fluid small-logo" alt=""></a>

      <ul class="list-group list-group-horizontal">
        <!-- <a href="/cart"><li class="list-group-item">
          <i class="bi bi-bag-check-fill">9</i>
        </li></a> -->
      
        <a href="/cart"><buton type="button" class="btn position-relative" style="padding-right: 60px;">
          <i class="bi bi-bag-check-fill"></i>
          <span class="position-absolute badge rounded-pill bg-danger">
          {{request.session.cart|length}}
          
          </span>
        </button></a>
        <!-- <li class="list-group-item"> -->
        {% if request.user.is_authenticated %}
        <div class="btn-group manoj1">
          <button type="button" class="user-name btn dropdown-toggle" data-bs-toggle="dropdown" data-bs-display="static"
            aria-expanded="false">{{request.user.first_name.0}}</button>
          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg-start">
            <li><a class="dropdown-item" href="/order">Order</a></li>
            <li><a class="dropdown-item" href="/accounts/LogOut">Log Out</a></li>
          </ul>
        </div>
<!--        <li class="list-group-item">cart</li>-->
        {% else %}
        <a href="/accounts/register">
          <li class="list-group-item">Sign Up</li>
        </a>
        <a href="/accounts/login">
          <li class="list-group-item">Login</li>
        </a>
        {% endif %}
      </ul>
    </div>
  </nav>
  <!-- search Section -->
  <div class="container">
    <div class="row d-flex">
      <form class="search-form">
        <input class="form-control fw-bold" type="" placeholder="Search for product" aria-label="Search">
        <button class="btn search-icon seaarch-icon-2" type="submit"><i class="bi bi-search "></i></button>
      </form>

    </div>
  </div>
</div>
<!-- sub nav bar start here -->
<div class="main-ulist">
  <div class="container-fluid">
    <div class="row">
      <div class="toggle"><i class="bi bi-list"></i></div>
      <div class="cross"><i class="bi bi-x-square"></i></div>
    </div>
  </div>
  <div class="container-fluid">
    <nav class="nav-bar">
      

    </nav>
  </div>
</div>
<!-- sub nav End -->

{%block content%}

{%endblock%}

<!-- Also Like Section End Here -->
<!-- footer section start here  -->
<div class="footer mx-3 pt-5">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-6">
        <div class="footer-main-body">
          <div class="footer-name">
            <h3>Shop Department</h3>
          </div>
          <div class="footer-product-name">
            <ul class="footer-ul-item">
              <li class=""><a class="" href="#">Sneakers &amp; Athletic</a></li>
              <li class=""><a class="" href="#">Athletic Apparel</a></li>
              <li class=""><a class="" href="#">Sandals</a></li>
              <li class=""><a class="" href="#">Jeans</a></li>
              <li class=""><a class="" href="#">Shirts &amp; Tops</a></li>
              <li class=""><a class="" href="#">Shorts</a></li>
              <li class=""><a class="" href="#">T-Shirts</a></li>
              <li class=""><a class="" href="#">Swimwear</a></li>
              <li class=""><a class="" href="#">Clogs &amp; Mules</a></li>
              <li class=""><a class="" href="#">Bags &amp; Wallets</a></li>
              <li class=""><a class="" href="#">Accessories</a></li>
              <li class=""><a class="" href="#">Sunglasses &amp; Eyewear</a></li>
              <li class=""><a class="" href="#">Watches</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-6">
        <div class="footer-main-body">
          <div class="footer-name">
            <h3>Account & shipping info</h3>
          </div>
          <div class="footer-product-name">
            <ul class="footer-ul-item">
              <li class=""><a class="" href="#">Your account</a></li>
              <li class=""><a class="" href="#">Shipping rates &amp; policies</a></li>
              <li class=""><a class="" href="#">Refunds &amp; replacements</a></li>
              <li class=""><a class="" href="#">Order tracking</a></li>
              <li class=""><a class="" href="#">Delivery info</a></li>
              <li class=""><a class="" href="#">Taxes &amp; fees</a></li>
            </ul>
          </div>
          <div class="about-us">
            <h3>About us</h3>
            <ul class="footer-ul-item">
              <li class=""><a class="" href="#">About company</a></li>
              <li class=""><a class="" href="#">Our team</a></li>
              <li class=""><a class="" href="#">Careers</a></li>
              <li class=""><a class="" href="#">News</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-6">
        <div class="footer-main-body">
          <div class="footer-name">
            <h3>Stay informed</h3>
          </div>
          <div class="footer-product-name">
            <div class="input-group mb-3">
              <input type="text" class="form-control fw-bold" placeholder="Your email" aria-label="Recipient's username"
                aria-describedby="basic-addon2">
              <span class="input-group-text" id="basic-addon2">Subscribe</span>
            </div>
            <p class="subs-theory">Subscribe to our newsletter to receive early discount offers, updates and new
              products info.</p>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

</body>

<!-- footer section End here  -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<!-- AOS Animation -->
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<!-- js slider -->
<!-- owl Carousel js -->
<script src="{% static 'js/owl.carousel.js ' %}"></script>
<!-- js -->
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/form.js' %}"></script>
<script src="{% static 'js/cart.js' %}"></script>
<script src="{% static 'js/splide.min.js' %}"></script>

<script>
  AOS.init();
</script>

<script>
  new Splide('.splide', {
    type: 'loop',
    perPage: 3,
    autoplay: true,
  }).mount();
</script>


</html>

Store/templates/cart.html
{% extends 'base.html' %}
{% load tshirt_tag %}
{%block content%}

<div class="container-fluid">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">S.no</th>
                <th scope="col">Tshirt Image</th>
                <th scope="col">Tshirt Name</th>
                <th scope="col">Size</th>
                <th scope="col">Price</th>
                <th scope="col">Discount</th>
                <th scope="col">Quantity</th>
                <th scope="col">After Discount Price</td>
                <th scope="col">Total</th>

            </tr>
        </thead>
        <tbody>
            {% for cart in cart %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>

                <td><img src="{{cart.tshirt.tshirt_img.url}}" alt="" class="rounded-circle img-fluid"
                        style="height: 70px;"></td>
                <td>{{cart.tshirt.tshirt_name}}</td>
                <td>{{cart.size}}</td>
                <td>{% rupee %}{{cart.size.price}}</td>
                <td>{{cart.tshirt.discount}}%</td>
                <td>{{cart.Quantity}}</td>
                <td>{% rupee %}{% clc_sale_price cart.size.price cart.tshirt.discount as sale_price %}{{sale_price}}
                </td>
                <td>{% rupee %}{% multiply cart.Quantity sale_price as total %}{{total}}</td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <th colspan="7"></th>
            <th colspan="">TOTAL :</th>
            <th colspan="">{% rupee %}{{cart|clc_total_payable_amount}}</th>
            </tr>
        </tfoot>
    </table>
    <div class="row d-flex justify-content-end">
        <div class="col-md-2">
            <a href="/checkout" style="text-decoration-line: none;"><p class="fw-bold btn btn-light">Continue To Check Out</p></a>
        </div>
       
    </div>
</div>


{%endblock%}

Store/templates/checkout_form.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% load tshirt_tag %}
{% block content %}
<div class="container mb-3">
  <div class="row">
    <div class="col-md-6">
      <form action="" method="post">
        {% csrf_token %}
        {{checkoutform|crispy}}
        <div class="container-fluid p-2">
          <div class="row">
            <input type="submit" class="btn signin-button text-white btn-sm text-uppercase fw-bold" value="Check Out">
          </div>
        </div>
      </form>
    </div>
    <div class="col-md-6">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Tshirt</th>
            <th scope="col">Size</th>
            <th scope="col">Price After Disc.</th>
          </tr>
        </thead>
        <tbody>
          {% for c in cart %}
          <tr>
            <th scope="row">{{forloop.counter}} .</th>
            <td class="fw-bold">{{c.size.tshirt.tshirt_name}}</td>
            <td class="fw-bold">{{c.size.size}}</td>
            <td class="fw-bold">{%rupee%}{% clc_sale_price c.size.price c.size.tshirt.discount %}</td>
          </tr>
          {% endfor %}
          <tr colspan="">
            <td colspan='3' class="fw-bold">Total Payable Amount :</td>
            <td class="fw-bold">{%rupee%}{{cart|clc_total_payable_amount}}.00</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

Store/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{%block content%}
<div class="row justify-content-center">
    <div class="col-4">
        <form class="row g-3 border shadow-sm mt-5 mb-5 pt-3 pb-3" id="signinform" action="/accounts/login"
            method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <div class="d-flex justify-content-end">
                <div class="form-check form-check-inline frgpswd">
                    <p class="fw-bold">Forgot password?</p>
                </div>
            </div>
            <div class="d-flex justify-content-around">
                <input type="submit" class="btn signin-button text-white btn-sm" value="Log In">
            </div>
               
           
            <!-- <div class="col-12">
                <label for="inputEmail4" class="form-label fw-bold">Email</label>
                <input type="email" class="form-control" id="inputEmail4">
            </div>
            <div class="col-12">
                <label for="inputPassword4" class="form-label fw-bold">Password</label>
                <input type="password" class="form-control" id="inputPassword4">
            </div>
            <div class="d-flex justify-content-end">
                <div class="form-check form-check-inline frgpswd">
                    <p class="fw-bold">Forgot password?</p>
                </div>
            </div>
            <div class="d-flex justify-content-between">
                <a href="/accounts/register"><button type="button" class="btn signin-button text-white btn-sm">Create An
                        Account </button></a>
                <input type="submit" class="btn signin-button text-white btn-sm" value="Log In">
            </div> -->
        </form>
    </div>
</div>
{%endblock%}

Store/templates/order.html
{% extends 'base.html'%}
{% load tshirt_tag %}
{% block content %}
<div class="container">
    <div class="row">
        <table class="table table-hover">
            <thead>
               <tr>
                   <!-- <th scope="col">#</th> -->
                   <th scope="col">Date</th>
                   <th scope="col">Item</th>
                   <th>Status</th>
               </tr>
           </thead>
           <tbody>
               {% for order in order %}
              
               <tr>  
                   <td>{{order.date|date}}</td>
                   <td>
                    
                       <table class="table table-sm">
                           <thead>
                               <tr>
                                   <th>#</th>
                                   <th>Image</th>
                                   <th>Product Name</th>
                                   <th>Price</th>
                                   <th>Quantity</th>
                                   <th>Total</th>
                               </tr>
                           </thead>
                           <tbody>
                               {% for orderitem in order.orderitem_set.all %}
                               <tr>
                                   <td>{{forloop.counter}}</td>
                                   <td> <img src="{{orderitem.tshirt.tshirt_img.url}}" alt="" height="70px;"> </td>
                                   <td>{{orderitem.tshirt.tshirt_name}}</td>
                                   <td>{%rupee%}{{orderitem.price}}</td>
                                   <td>{{orderitem.quantity}}</td>
                                   <td>{%rupee%}{% multiply orderitem.price orderitem.quantity %}</td>


                               </tr>
                               {% endfor %}
                           </tbody>
                       </table>
                   </td>
                   <td>{{order.order_status}}</td>
               </tr>
               {% endfor %}
           </tbody>
       </table>
    </div>
</div>

{% endblock %}

Store/templates/payment_failed.html
{% extends 'base.html'%}
{% block content %}
<div class="container mb-5">
    <div class="row">
        <div class="card text-center alert alert-danger">
            <div class="card-body">
                <h5 class="card-title">Payment Failed !</h5>
                <p>Go To Cart And Try Again...</p>
            </div>
        </div>
    </div>
</div>


{% endblock %}